version: "3.9"

services:
  fit-app:
    build: . # path to dockerfile
    ports:
      - "3000:80" # Access app at http://localhost:3000
    volumes:
      - ./public:/var/www/html/fit-app
      - ./php:/var/www/html/fit-app/php
